# Generated by Django 5.0.6 on 2024-06-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_questions_content_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer_text',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='questions',
            name='content_text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
