# Generated by Django 5.0.6 on 2024-06-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_questions_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer_text',
            field=models.CharField(max_length=120),
        ),
    ]
